### ISSUE TITLE
Why not .all()?

### ISSUE THREAD

**Issue by Matt-Eva** [learn-co-curriculum/python-p3-crud-with-sqlalchemy#7]
### Canvas Link

https://learning.flatironschool.com/courses/6049/pages/create-read-update-and-delete-with-sqlalchemy?module_item_id=468028

### Concern

Any reason we're using the `[name for name in session.query(Student.name)]` syntax instead of `session.query(Student.name).all()`? The latter seems a little cleaner.

**Comment by professor-ben** [comment]
This is a great question with an answer that was a bit too complicated for the students at this point in the curriculum (i.e. pre-time and space complexity). The two there are more or less equivalent, but as soon as you start processing the data in the comprehension instead of just storing it, the space complexity goes way down because whole records aren't stored in memory. I recently removed an explanation because it required a couple minutes of extra explanation even for my curriculum colleagues- didn't seem appropriate for the lesson.

I think you're right that this should be handled with `.all()` for the added clarity. This is a very long lesson to begin with, but I'll see if I can provide a very brief intro to space complexity as well.

**Comment by Matt-Eva** [comment]
Makes sense, thank you! Yeah, that does seem slightly too high level for students at this point. We can always point students toward relevant reading, too - seems like an appropriate time to do so, for those who are interested. 

Alternatively, this whole convo could be a separate lesson specifically talking about space complexity, since this lesson already is pretty long. Just spitballing - definitely not trying to throw more onto your plate haha. Thanks again!
